---
ENABLE:
  - ACTION
  - COPYPASTE
  - CSS
  - HTML
  - JAVASCRIPT
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - TYPESCRIPT
  - XML
  - YAML
  - ENV
  - TSX
  - JSX
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  # Disabled because it is painfully slow when running locally
  - REPOSITORY_GRYPE
  # No ruleset defined
  - REPOSITORY_LS_LINT
  - REPOSITORY_SEMGREP
  - SPELL_PROSELINT
  - SPELL_VALE
  # AirBnb styleguide is used in this project
  - TYPESCRIPT_STANDARD
  - JAVASCRIPT_STANDARD
  - JSON_ESLINT_PLUGIN_JSONC
  - JAVASCRIPT_ES
LINTER_RULES_PATH: ./linters
REPOSITORY_SYFT_ARGUMENTS: --exclude '**/node_modules'
REPOSITORY_TRUFFLEHOG_ARGUMENTS: --exclude-paths=linters/exclude.txt
REPOSITORY_KICS_RULES_PATH: ./linters
REPOSITORY_KICS_CONFIG_FILE: .kics.config.json
ADDITIONAL_EXCLUDED_DIRECTORIES:
  # Excluded because some linters do not respect gitignored directories and running mega-linter locally can be really slow and cause false positives
  - node_modules
  - .next
  - .idea
  - .yarn
  - megalinter-reports
PRE_COMMANDS:
  - command: corepack enable
    cwd: "workspace"
    secured_env: true
  - command: yarn set version 4.4.0
    cwd: "workspace"
    secured_env: true
  - command: CI=true
    cwd: "workspace"
    secured_env: true
    output_variables: [CI]
  - command: yarn install --immutable
    cwd: "workspace"
    secured_env: true
