---
APPLY_FIXES: ALL
ENABLE:
  - ACTION
  - COPYPASTE
  - CSS
  - HTML
  - JAVASCRIPT
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - TYPESCRIPT
  - XML
  - YAML
  - ENV
  - TSX
  - JSX
LINTER_RULES_PATH: ./portfolio
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - .idea
PRE_COMMANDS:
  - command: yarn install --frozen-lockfile --non-interactive
    cwd: "portfolio"
    secured_env: true
