---
services:
  portfolio:
    container_name: portfolio
    build:
      context: ./portfolio
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    security_opt:
      - apparmor:docker-default
    networks:
      - my_network

networks:
  my_network:
    external: true
